### ISSUE TITLE
Remove git fields in backend

### ISSUE THREAD

**Issue by bvkatwijk** [unicorn-wizards/Testdertesten#12]
https://github.com/unicorn-wizards/Testdertesten/blob/2209ad8834824c9cd194c3242d91f7c2f0e05563/backend/package.json#L9

There are fields in `./backend/package.json` that should not be in there.
Easiest fix is probably by regenerating the file (re-run `npm init` in the backend folder and commit the changes

**Comment by ThijsssSchroder** [comment]
Review changes please!
