### ISSUE TITLE
Create express server in backend

### ISSUE THREAD

**Issue by bvkatwijk** [unicorn-wizards/Testdertesten#4]
https://www.npmjs.com/package/express

See project of last week for inspiration

Requirements:
when i run `npm run dev` the backend project should start on localhost:3000
When I go to the browser http://localhost:3000 i want to see 'Hello World'

**Comment by FlorfK** [comment]
Must he say hello world?
Why not 'lol i guess'

**Comment by bvkatwijk** [comment]
No I am project manager I want `Hello World` plox plox for realz
